import {query} from '../config/db.js';
import {matches} from '../repositories/matchRepository.js';
import {disputes} from '../repositories/disputeRepository.js';
import {teams} from '../repositories/teamRepository.js';
import {notifyUsers} from './notificationService.js';
import {advanceWinner} from './bracketService.js';
export async function captainOwnsMatch(match,userId){return [match.team1_id,match.team2_id].includes((await query('SELECT id FROM teams WHERE captain_id=$1 AND id=ANY($2)',[userId,[match.team1_id,match.team2_id].filter(Boolean)])).rows[0]?.id);}
export async function submitResult(id,userId,score1,score2,io){const m=await matches.get(id);if(!m)throw Object.assign(new Error('Match not found'),{status:404});if(!await captainOwnsMatch(m,userId))throw Object.assign(new Error('Only a participating Team Captain can submit the result'),{status:403});if(m.status!=='LIVE'&&m.status!=='SCHEDULED')throw Object.assign(new Error('This match cannot accept a result in its current state'),{status:400});if(score1<0||score2<0||score1===score2)throw Object.assign(new Error('Scores must be non-negative and cannot be tied'),{status:400});const winnerId=score1>score2?m.team1_id:m.team2_id;const updated=await matches.update(id,{score1,score2,status:'AWAITING_CONFIRMATION',winner_id:winnerId});const opponentTeam=m.team1_id===winnerId?m.team2_id:m.team1_id;const cap=(await query('SELECT captain_id FROM teams WHERE id=$1',[opponentTeam])).rows[0]?.captain_id;await notifyUsers([cap],`Result submitted for ${m.team1_name} vs ${m.team2_name}. Please confirm or dispute.`,io,m.org_id);return updated;}
export async function confirmResult(id,userId,io){const m=await matches.get(id);if(!m)throw Object.assign(new Error('Match not found'),{status:404});if(m.status!=='AWAITING_CONFIRMATION')throw Object.assign(new Error('Match is not awaiting confirmation'),{status:400});const opposing= m.team1_id===m.winner_id?m.team2_id:m.team1_id;const ok=await query('SELECT 1 FROM teams WHERE id=$1 AND captain_id=$2',[opposing,userId]);if(!ok.rowCount)throw Object.assign(new Error('Only the opposing Team Captain can confirm'),{status:403});const u=await matches.update(id,{status:'CONFIRMED'});await advanceWinner(id,u.winner_id,io,m.org_id);const caps=(await query('SELECT captain_id FROM teams WHERE id IN ($1,$2)',[m.team1_id,m.team2_id])).rows.map(x=>x.captain_id);await notifyUsers(caps,`Match confirmed: ${m.team1_name} ${m.score1}–${m.score2} ${m.team2_name}.`,io,m.org_id);return u;}
export async function raiseDispute(id,userId,reason,io){const m=await matches.get(id);if(!m)throw Object.assign(new Error('Match not found'),{status:404});if(m.status!=='AWAITING_CONFIRMATION')throw Object.assign(new Error('Only submitted results can be disputed'),{status:400});if(!await captainOwnsMatch(m,userId))throw Object.assign(new Error('Only a participating Team Captain can dispute'),{status:403});if(!reason?.trim())throw Object.assign(new Error('A dispute reason is required'),{status:400});const d=await disputes.create(id,userId,reason.trim());await matches.update(id,{status:'DISPUTED'});const refs=(await query(`SELECT m.user_id FROM org_memberships m WHERE m.org_id=$1 AND m.role='REFEREE'`,[m.org_id])).rows.map(x=>x.user_id);await notifyUsers(refs,`Dispute raised for ${m.team1_name} vs ${m.team2_name}: ${reason.trim()}`,io,m.org_id);return d;}
export async function resolveDispute(disputeId,userId,outcome,io){const d=await disputes.get(disputeId);if(!d)throw Object.assign(new Error('Dispute not found'),{status:404});if(!['UPHOLD','OVERTURN'].includes(outcome))throw Object.assign(new Error('Resolution must be UPHOLD or OVERTURN'),{status:400});const r=await disputes.resolve(disputeId,userId,outcome);let newWinner=d.match_status==='DISPUTED'?null:null;const match=await matches.get(d.match_id);if(outcome==='UPHOLD')newWinner=match.winner_id;else newWinner=match.winner_id===match.team1_id?match.team2_id:match.team1_id;const u=await matches.update(d.match_id,{status:'RESOLVED',winner_id:newWinner});await advanceWinner(d.match_id,newWinner,io,d.org_id);const caps=(await query('SELECT captain_id FROM teams WHERE id IN ($1,$2)',[match.team1_id,match.team2_id])).rows.map(x=>x.captain_id);await notifyUsers(caps,`Dispute resolved as ${outcome.toLowerCase()} for ${match.team1_name} vs ${match.team2_name}.`,io,d.org_id);return {dispute:r,match:u};}
export async function startMatch(id,userId,io){const m=await matches.get(id);if(!m)throw Object.assign(new Error('Match not found'),{status:404});const member=await query('SELECT role FROM org_memberships WHERE user_id=$1 AND org_id=$2',[userId,m.org_id]);if(!member.rowCount||!['TEAM_CAPTAIN','TOURNAMENT_ORGANIZER','REFEREE'].includes(member.rows[0].role))throw Object.assign(new Error('Not authorized'),{status:403});const u=await matches.update(id,{status:'LIVE',scheduled_at:new Date()});io?.to(`org:${m.org_id}`).emit('match:update',u);return u;}
