import {tournaments} from '../repositories/tournamentRepository.js';import {createTournament,ensureTournamentAccess,registerTeam} from '../services/tournamentService.js';import {generateBracket} from '../services/bracketService.js';import {teams} from '../repositories/teamRepository.js';import {query} from '../config/db.js';import {notifyTournamentCaptains} from '../services/notificationService.js';
export const list=async(req,res)=>{const m=await query('SELECT 1 FROM org_memberships WHERE org_id=$1 AND user_id=$2',[req.params.orgId,req.user.id]);if(!m.rowCount)return res.status(403).json({message:'You do not have access to this host'});res.json(await tournaments.list(req.params.orgId));};
export const get=async(req,res)=>{const x=await ensureTournamentAccess(req.params.id,req.user.id);res.json({tournament:x.t,teams:await tournaments.teams(req.params.id),matches:await (await import('../repositories/matchRepository.js')).matches.list(req.params.id),disputes:await (await import('../repositories/disputeRepository.js')).disputes.forTournament(req.params.id)});};
export const create=async(req,res)=>{const m=await query("SELECT role FROM org_memberships WHERE org_id=$1 AND user_id=$2",[req.params.orgId,req.user.id]);if(m.rows[0]?.role!=='TOURNAMENT_ORGANIZER')return res.status(403).json({message:'Tournament Organizer role required'});if(!req.body.name||!req.body.maxTeams||!req.body.startDate)return res.status(400).json({message:'Name, maximum teams and start date are required'});res.status(201).json(await createTournament(req.params.orgId,req.body));};
export const update=async(req,res)=>{const x=await ensureTournamentAccess(req.params.id,req.user.id);if(x.role!=='TOURNAMENT_ORGANIZER')return res.status(403).json({message:'Tournament Organizer role required'});res.json(await tournaments.update(req.params.id,{name:req.body.name,maxTeams:req.body.maxTeams,startDate:req.body.startDate,rules:req.body.rules||''}));};
export const status=async(req,res)=>{const x=await ensureTournamentAccess(req.params.id,req.user.id);if(x.role!=='TOURNAMENT_ORGANIZER')return res.status(403).json({message:'Tournament Organizer role required'});const allowed={open:['DRAFT','REGISTRATION_CLOSED'],close:['REGISTRATION_OPEN'],start:['REGISTRATION_CLOSED']};const action=req.params.action;const map={open:'REGISTRATION_OPEN',close:'REGISTRATION_CLOSED',start:'IN_PROGRESS'};if(!allowed[action]?.includes(x.t.status))return res.status(400).json({message:`Invalid tournament state for ${action}`});const t=await tournaments.status(req.params.id,map[action]);if(action==='open')await notifyTournamentCaptains(req.params.id,'Registration is now open.',req.app.get('io'),t.org_id);if(action==='start')await notifyTournamentCaptains(req.params.id,'Tournament has started.',req.app.get('io'),t.org_id);res.json(t)};
export const register=async(req,res)=>res.status(201).json(await registerTeam(req.params.id,req.user.id,req.body.name));
export const addPlayer=async(req,res)=>{const team=await teams.get(req.params.id);if(!team)return res.status(404).json({message:'Team not found'});const membership=await query('SELECT role FROM org_memberships WHERE org_id=$1 AND user_id=$2',[team.org_id,req.user.id]);if(!membership.rowCount)return res.status(403).json({message:'You do not have access to this host'});if(team.captain_id!==req.user.id)return res.status(403).json({message:'Only the Team Captain can manage this roster'});if(team.tournament_status!=='DRAFT'&&team.tournament_status!=='REGISTRATION_OPEN')return res.status(400).json({message:'Roster changes are closed once the tournament starts'});const u=(await query("SELECT u.id FROM users u JOIN org_memberships m ON m.user_id=u.id AND m.org_id=$1 WHERE u.email=$2 AND m.role='PLAYER'",[team.org_id,req.body.email])).rows[0];if(!u)return res.status(404).json({message:'Player email not found'});res.status(201).json(await teams.addPlayer(team.id,u.id));};
export const removePlayer=async(req,res)=>{const team=await teams.get(req.params.id);if(!team||team.captain_id!==req.user.id)return res.status(403).json({message:'Only the Team Captain can manage this roster'});await teams.removePlayer(team.id,req.params.userId);res.status(204).send()};
export const generate=async(req,res)=>{const x=await ensureTournamentAccess(req.params.id,req.user.id);if(x.role!=='TOURNAMENT_ORGANIZER')return res.status(403).json({message:'Tournament Organizer role required'});if(x.t.status!=='REGISTRATION_CLOSED')return res.status(400).json({message:'Close registration before generating the bracket'});res.json(await generateBracket(req.params.id,req.app.get('io'),x.t.org_id));};

export const playerList=async(req,res)=>{const team=await teams.get(req.params.id);if(!team)return res.status(404).json({message:'Team not found'});const membership=await query('SELECT 1 FROM org_memberships WHERE org_id=$1 AND user_id=$2',[team.org_id,req.user.id]);if(!membership.rowCount)return res.status(403).json({message:'You do not have access to this host'});res.json(await teams.members(team.id));};
